/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_hud_jnvi_api_JNVIAPI */

#ifndef _Included_uk_ac_hud_jnvi_api_JNVIAPI
#define _Included_uk_ac_hud_jnvi_api_JNVIAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    nativeMultiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_nativeMultiply
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
