/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_hud_jnvi_api_JNVIAPI */

#ifndef _Included_uk_ac_hud_jnvi_api_JNVIAPI
#define _Included_uk_ac_hud_jnvi_api_JNVIAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_ac_hud_jnvi_api_JNVIAPI_TYPE_DOUBLE
#define uk_ac_hud_jnvi_api_JNVIAPI_TYPE_DOUBLE 1L
#undef uk_ac_hud_jnvi_api_JNVIAPI_TYPE_FLOAT
#define uk_ac_hud_jnvi_api_JNVIAPI_TYPE_FLOAT 2L
#undef uk_ac_hud_jnvi_api_JNVIAPI_TYPE_INT
#define uk_ac_hud_jnvi_api_JNVIAPI_TYPE_INT 3L
/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    getVersion0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_getVersion0
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    add
 * Signature: (BJJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_add
  (JNIEnv *, jclass, jbyte, jlong, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    sub
 * Signature: (BJJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_sub
  (JNIEnv *, jclass, jbyte, jlong, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    mul
 * Signature: (BJJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_mul
  (JNIEnv *, jclass, jbyte, jlong, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    div
 * Signature: (BJJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_div
  (JNIEnv *, jclass, jbyte, jlong, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    dot
 * Signature: (BJJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_dot
  (JNIEnv *, jclass, jbyte, jlong, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    sum
 * Signature: (BJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_sum
  (JNIEnv *, jclass, jbyte, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    sqrt
 * Signature: (BJJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_sqrt
  (JNIEnv *, jclass, jbyte, jlong, jlong, jint);

/*
 * Class:     uk_ac_hud_jnvi_api_JNVIAPI
 * Method:    rsqrt
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_hud_jnvi_api_JNVIAPI_rsqrt
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
